### ISSUE TITLE
Magisk新的下载地址也有点慢，一下一个不吱声，下到一半就g了

### ISSUE THREAD

**Issue by zht163** [abing7k/redroid-script#1]
要么科学上网，要么自己先下下来，然后弄个快点的地址，替换到stuffs/magisk.py 的第十行
![image](https://github.com/abing7k/redroid-script/assets/48507961/7704e717-3e29-4809-aca6-2c627d66599f)

**Comment by abing7k** [comment]
You can try finding a mirror website,and download it again.

**Comment by abing7k** [comment]
@zht163 I have updated the readme document,and you can run the image I created

**Comment by ZZZ-zero** [comment]
> @zht163 I have updated the readme document,and you can run the image I created

再次失效，我更改使用为https://hub.fgit.cf/HuskyDG/magisk-files/releases/download/R657C2E65-kitsune/app-release.apk

**Comment by zht163** [comment]
Ok, thank you, brother
