### ISSUE TITLE
hi what is your arm hardware info for images(arm64)?

### ISSUE THREAD

**Issue by lls2wow** [abing7k/redroid-script#10]
I use kunpeng916 server and no graphic card, I see you use arm based cpu and amd graphic card, I doubt wheather exist arm based amd  graphic driver.

**Comment by lls2wow** [comment]
<img width="454" alt="image" src="https://github.com/abing7k/redroid-script/assets/12065810/e1192600-cc97-4fab-98b4-e92465cf4b86">

I failed start magisk

**Comment by abing7k** [comment]
I'm using an arm server from Oracle Cloud
