### ISSUE TITLE
Doesn't connect to android

### ISSUE THREAD

**Issue by dima23113** [abing7k/redroid-script#13]
I tried everything, but there is no connection. Tell me what to do?

![изображение](https://github.com/user-attachments/assets/f53b44cd-ad2c-4d59-8d85-41aea1d4b8ee)

**Comment by dima23113** [comment]
when i try dot it via official image all works fine

**Comment by dima23113** [comment]
![изображение](https://github.com/user-attachments/assets/879dc780-a04f-4150-9d86-a3f1456a139a)

**Comment by abing7k** [comment]
Even if amd can run, a lot of software can't run, and efficiency is very low

**Comment by abing7k** [comment]
Maybe your configuration is too low, or you don't have the appropriate environment installed, see the official project for details
