### ISSUE TITLE
scrcpy-web adb connect failed

### ISSUE THREAD

**Issue by MessInWind** [abing7k/redroid-script#6]
![image](https://github.com/abing7k/redroid-script/assets/110244205/bf328772-aa3d-4731-a438-405651f1e847)
![image](https://github.com/abing7k/redroid-script/assets/110244205/577c3006-2929-47f6-be3e-01492097cb6a)
![image](https://github.com/abing7k/redroid-script/assets/110244205/72c3508b-ace1-4eeb-a963-6e540f04818e)
![image](https://github.com/abing7k/redroid-script/assets/110244205/0d21cd12-a1cc-4855-bee8-6835a447b62f)

amd64
help !

**Comment by MessInWind** [comment]
![image](https://github.com/abing7k/redroid-script/assets/110244205/486fc7ed-f6c3-4f71-b08f-741675efb301)
眼睁睁看着爆内存怎么回事

**Comment by MessInWind** [comment]
启动scrcpy-web爆内存，redroid也爆内存，我2c2g的amd64

**Comment by MessInWind** [comment]
#solved.
use ubuntu 20.04 amd64
never use scrcpy-web, instead scrcpy is fine.
if you want to use qq, some of the versions may crash, I'm using 8.9.78.apk, but the qq application require bigger RAM size. my server is 2G, not enough to run magisk, shamrock and qq. maybe 4G.
by the way, qq is not stable on amd64.

**Comment by abing7k** [comment]
@ZZZ-zero redroid至少4G内存
